### ISSUE TITLE
Error found in the log

### ISSUE THREAD

**Issue by rjucf** [UCF/UCF-GMUCF-Theme#45]
[Mon Jan 28 11:20:11 2019] [error] [client 10.208.16.89] PHP Fatal error:  Call to undefined method WP_Error::error() in ~/wordpress/wp-content/themes/UCF-GMUCF-Theme/functions.php on line 237

**Comment by jmbarne3** [comment]
I believe this is just outdated code. The new function should be: `WP_Error->get_error_message()` or in this case `$rss->get_error_message()`, which will return the first error message in the `WP_Error` object.

Here's a link to the code for easy reference:

https://github.com/UCF/UCF-GMUCF-Theme/blob/96b8cae73cc83f2e1e9539b3418ba88419e1f5a9/functions.php#L237
