### ISSUE TITLE
Announcements search is not displaying all announcements

### ISSUE THREAD

**Issue by rjucf** [UCF/UCF-GMUCF-Theme#50]
When typing in an announcement title in the "GMUCF Announcements" field not all announcements are displayed in the search results. To reproduce the issue, Try searching for an "Ongoing Announcement" here https://www.ucf.edu/announcements/

**Comment by cadieb** [comment]
This was resolved in the Today-Utilities plugin:
https://github.com/UCF/Today-Utilities/releases/tag/v1.0.2
https://github.com/UCF/Today-Utilities/pull/14
